#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# See more in https://faun.pub/why-using-pre-push-git-hooks-with-husky-is-not-always-a-good-idea-6233b8afcf83
git diff HEAD --quiet && yarn test --run --silent --reporter default --coverage
